/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  user2
 * Created: 09.01.2017
 */

-- v3.00.1 - v3.00.2

-- final script

CREATE UNIQUE INDEX CLOSEDCASH_INX_MONEY ON CLOSEDCASH (MONEY);

CREATE TABLE _ROLES (                                                                                                                  
    ID VARCHAR NOT NULL, 
    ROWNUMBER INT NOT NULL, 
    BONUS_FROM_SALES DOUBLE PRECISION,
    SESSION_PLAN DOUBLE PRECISION,
    TEAMBONUS_COEF DOUBLE PRECISION,
    NAME VARCHAR NOT NULL,
    PERMISSIONS BYTEA,
    PRIMARY KEY (ID));

INSERT INTO _ROLES (ID, ROWNUMBER, BONUS_FROM_SALES, SESSION_PLAN,  TEAMBONUS_COEF,  NAME, PERMISSIONS) SELECT B.ROLE_ID, B.ROWNUMBER, B.INDIVBONUS_FROM_SALES, B.SESSION_INDIV_PLAN,  B.TEAMBONUS_COEF,  R.NAME, R.PERMISSIONS FROM BONUSCONFIGROLES B, ROLES R WHERE B.ROLE_ID = R.ID;

ALTER TABLE PEOPLE DROP CONSTRAINT PEOPLE_FK_1;
DROP TABLE ROLES;

CREATE TABLE ROLES (                                                                                                                  
    ID VARCHAR NOT NULL, 
    ROWNUMBER INT NOT NULL, 
    BONUS_FROM_SALES DOUBLE PRECISION,
    SESSION_PLAN DOUBLE PRECISION,
    TEAMBONUS_COEF DOUBLE PRECISION,
    NAME VARCHAR NOT NULL,
    PERMISSIONS BYTEA,
    PRIMARY KEY (ID));
INSERT INTO ROLES (ID, ROWNUMBER, BONUS_FROM_SALES, SESSION_PLAN,  TEAMBONUS_COEF, NAME, PERMISSIONS) SELECT ID, ROWNUMBER, BONUS_FROM_SALES, SESSION_PLAN,  TEAMBONUS_COEF,  NAME, PERMISSIONS FROM _ROLES;
INSERT INTO ROLES(ROWNUMBER, ID, BONUS_FROM_SALES, SESSION_PLAN, TEAMBONUS_COEF, NAME, PERMISSIONS) VALUES(5, 'TEAMBONUSCONFIG', 0.01, 175000.0, 0.0, 'Teambonus configuration role', $FILE{/com/openbravo/pos/templates/Role.Teambonus.xml} );
UPDATE ROLES SET PERMISSIONS = $FILE{/com/openbravo/pos/templates/Role.Administrator.xml} WHERE ID = '0';
UPDATE RESOURCES SET CONTENT = $FILE{/com/openbravo/pos/templates/Menu.Root.txt} WHERE ID = '14';
--UPDATE ROLES SET BONUS_FROM_SALES = (SELECT TEAMBONUS_FROM_SALES FROM BONUSCONFIGROLES WHERE ID = '0') WHERE ID = 'TEAMBONUSCONFIG';
--UPDATE ROLES SET SESSION_PLAN = (SELECT TBSESSION_TEAM_PLAN FROM BONUSCONFIGROLES WHERE ID = '0') WHERE ID = 'TEAMBONUSCONFIG';

DROP TABLE _ROLES;
ALTER TABLE PEOPLE ADD CONSTRAINT PEOPLE_FK_1 FOREIGN KEY (ROLE) REFERENCES ROLES(ID);

DROP TABLE BONUSCONFIGROLES;
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};
