/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.ddns.evcalyptus.bonus;

import com.openbravo.basic.BasicException;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.util.UUID;
import net.ddns.evcalyptus.bonus.DataLogicBonusConfig;


/**
 *
 * @author user2
 */


public class BonusView extends javax.swing.JPanel implements EditorRecord {
    
    private Object m_oId;
    //AppView app;
    DataLogicBonusConfig dl_BC;
    private int rownumber;
    
    
    /** Creates new form RolesEditor */
    public BonusView(DirtyManager dirty, AppView app) {
    
        dl_BC  = (DataLogicBonusConfig) app.getBean("net.ddns.evcalyptus.bonus.DataLogicBonusConfig");
        
        initComponents();
        
        bonusofsales.getDocument().addDocumentListener(dirty);
        bonusplan.getDocument().addDocumentListener(dirty);
        teambonuscoef.getDocument().addDocumentListener(dirty);
        m_jName.getDocument().addDocumentListener(dirty);
        m_jText.getDocument().addDocumentListener(dirty);
        
         
        
        
        writeValueEOF();
    }
    
    public void writeValueEOF() {
        m_oId = null;
        rownumber = -1;
        bonusofsales.setText(null);
        bonusplan.setText(null);
        teambonuscoef.setText(null);
        m_jName.setText(null);
        m_jText.setText(null);
        bonusofsales.setEnabled(false);
        bonusplan.setEnabled(false);
        teambonuscoef.setEnabled(false);
        m_jName.setEnabled(false);
        m_jText.setEnabled(false);
    }
    
    public void writeValueInsert() {
        m_oId = null;
        rownumber = -1;
        bonusofsales.setText(null);
        bonusplan.setText(null);
        teambonuscoef.setText(null);
        m_jName.setText(null);
        m_jText.setText(null);
        bonusofsales.setEnabled(true);
        bonusplan.setEnabled(true);
        teambonuscoef.setEnabled(true);
        m_jName.setEnabled(true);
        m_jText.setEnabled(true);
    }
    
    public void writeValueDelete(Object value) {

        Object[] role = (Object[]) value;
        m_oId = role[0];
        rownumber = (int)role[1];
        bonusofsales.setText(Formats.DOUBLE.formatValue(role[2]));
        bonusplan.setText(Formats.DOUBLE.formatValue(role[3]));
        teambonuscoef.setText(Formats.DOUBLE.formatValue(role[4]));
        m_jName.setText(Formats.STRING.formatValue(role[5]));
        m_jText.setText(Formats.BYTEA.formatValue(role[6]));
        m_jText.setCaretPosition(0);
        bonusofsales.setEnabled(false);
        bonusplan.setEnabled(false);
        teambonuscoef.setEnabled(false);
        m_jName.setEnabled(false);
        m_jText.setEnabled(false);
    }   
    
    public void writeValueEdit(Object value) {

        Object[] role = (Object[]) value;
        m_oId = role[0];
        rownumber = (int)role[1];
        bonusofsales.setText(Formats.DOUBLE.formatValue(role[2]));
        bonusplan.setText(Formats.DOUBLE.formatValue(role[3]));
        teambonuscoef.setText(Formats.DOUBLE.formatValue(role[4]));
        m_jName.setText(Formats.STRING.formatValue(role[5]));
        m_jText.setText(Formats.BYTEA.formatValue(role[6]));
        m_jText.setCaretPosition(0);
        bonusofsales.setEnabled(true);
        bonusplan.setEnabled(true);
        teambonuscoef.setEnabled(true);
        m_jName.setEnabled(true);
        m_jText.setEnabled(true);
    }    
    
    public Object createValue() throws BasicException {

        Object[] role = new Object[7];
        role[0] = m_oId == null ? UUID.randomUUID().toString() : m_oId;
        role[1] = rownumber == -1 ? dl_BC.countRolesRows()+1 : rownumber;
        role[2] = Formats.DOUBLE.parseValue(bonusofsales.getText());
        role[3] = Formats.DOUBLE.parseValue(bonusplan.getText());
        role[4] = Formats.DOUBLE.parseValue(teambonuscoef.getText());
        role[5] = m_jName.getText();
        role[6] = Formats.BYTEA.parseValue(m_jText.getText());
        return role;
    }
    
    public Component getComponent() {
        return this;
    }
    
    public void refresh() {
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bonusofsales = new javax.swing.JTextField();
        bonusplan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_jText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        teambonuscoef = new javax.swing.JTextField();

        jLabel2.setText(AppLocal.getIntString("Label.Name")); // NOI18N

        jLabel1.setText(AppLocal.getIntString("Label.Bonus as share of sales"));

        jLabel3.setText(AppLocal.getIntString("Label.Bonus sales plan"));

        m_jText.setColumns(20);
        m_jText.setRows(5);
        jScrollPane1.setViewportView(m_jText);

        jLabel4.setText(AppLocal.getIntString("Label.Team bonus coef"));

        teambonuscoef.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_jName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bonusofsales)
                            .addComponent(bonusplan)
                            .addComponent(teambonuscoef, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(m_jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bonusofsales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bonusplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(teambonuscoef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bonusofsales;
    private javax.swing.JTextField bonusplan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m_jName;
    private javax.swing.JTextArea m_jText;
    private javax.swing.JTextField teambonuscoef;
    // End of variables declaration//GEN-END:variables
    
}